/**
 * Numeric character reference parity (PR #77 rework round 1).
 *
 * The verifier found an undisclosed divergence: expat REJECTS numeric char
 * refs to XML-1.0-invalid code points ("reference to invalid character
 * number") while fast-xml-parser resolved-and-dropped them (a&#8;b -> "ab").
 * air-ts now rejects them pre-parse (src/xml.ts rejectInvalidCharRefs).
 *
 * PROVENANCE: every accept/reject expectation below was produced by running
 * the oracle (`xml.etree.ElementTree.fromstring`) at rework time; the fixture
 * file tests/fixtures/charref.json holds byte-exact oracle model.json and
 * canonical.air.xml for the valid-ref resolution cases (generated by running
 * air.parser + air.model_dump + air.canonicalizer on the exact `xml` strings).
 */

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { parse, canonicalize, serializeModel, parseOutcome } from "../src/index.js";
import { XmlParseError } from "../src/xml.js";
import { byteDiff } from "./harness.js";

const REJECT_MSG = "reference to invalid character number";

/** Wrap a text payload in a minimal system document. */
const doc = (text: string): string => `<system name="t"><t>${text}</t></system>`;

// Oracle-verified REJECT cases (expat: "reference to invalid character number").
const INVALID_REFS: string[] = [
  "&#0;",
  "&#8;",
  "&#11;",
  "&#12;",
  "&#27;",
  "&#31;",
  "&#55296;", // 0xD800 low surrogate bound
  "&#57343;", // 0xDFFF high surrogate bound
  "&#65534;", // 0xFFFE
  "&#65535;", // 0xFFFF
  "&#1114112;", // 0x110000 (one past max)
  "&#99999999999;", // far beyond Unicode
  "&#x0;",
  "&#x8;",
  "&#xB;",
  "&#x1F;",
  "&#xD800;",
  "&#xFFFE;",
  "&#x110000;",
];

// Oracle-verified ACCEPT cases (XML 1.0 Char production boundaries).
const VALID_REFS: string[] = [
  "&#9;",
  "&#10;",
  "&#13;",
  "&#32;",
  "&#127;",
  "&#55295;", // 0xD7FF
  "&#57344;", // 0xE000
  "&#65533;", // 0xFFFD
  "&#65536;", // 0x10000
  "&#1114111;", // 0x10FFFF
  "&#65;",
  "&#x41;",
  "&#x2764;",
  "&#xD7FF;", // uppercase hex digits (oracle accepts)
  "&#xd7ff;", // lowercase hex digits
];

describe("invalid numeric char refs are rejected (oracle parity)", () => {
  for (const ref of INVALID_REFS) {
    it(`parse rejects ${ref} in element text`, () => {
      expect(() => parse(doc(`a${ref}b`))).toThrowError(REJECT_MSG);
      expect(() => parse(doc(`a${ref}b`))).toThrowError(XmlParseError);
    });
  }

  it("rejects an invalid ref in an ATTRIBUTE value (oracle: REJECT)", () => {
    expect(() => parse('<system name="a&#8;b"><t/></system>')).toThrowError(
      REJECT_MSG,
    );
  });

  it("canonicalize rejects too (same pre-parse gate)", () => {
    expect(() => canonicalize(doc("a&#11;b"))).toThrowError(REJECT_MSG);
  });

  it("parseOutcome reports reject (not crash) for an invalid ref", () => {
    const out = parseOutcome(doc("a&#8;b"));
    expect(out.status).toBe("reject");
    if (out.status === "reject") {
      expect(out.reason).toContain("XmlParseError");
      expect(out.reason).toContain(REJECT_MSG);
    }
  });
});

describe("valid numeric char refs are accepted (oracle parity)", () => {
  for (const ref of VALID_REFS) {
    it(`parse accepts ${ref} in element text`, () => {
      expect(() => parse(doc(`a${ref}b`))).not.toThrow();
    });
  }
});

describe("contexts where expat does NOT process refs (oracle: ACCEPT)", () => {
  it("invalid ref inside a comment is not rejected", () => {
    expect(() =>
      parse('<system name="t"><!-- &#8; --><t>x</t></system>'),
    ).not.toThrow();
  });

  it("invalid ref inside CDATA is not rejected", () => {
    expect(() =>
      parse('<system name="t"><t><![CDATA[&#8;]]></t></system>'),
    ).not.toThrow();
  });

  it("invalid ref inside a processing instruction is not rejected", () => {
    expect(() =>
      parse('<system name="t"><t><?pi &#8; ?>x</t></system>'),
    ).not.toThrow();
  });

  it("&amp;#8; is an escaped ampersand, not a reference", () => {
    expect(() => parse('<system name="t"><t>&amp;#8;</t></system>')).not.toThrow();
  });

  it("a valid ref before an invalid literal sequence does not false-positive", () => {
    // &#38;#0; = resolved '&' followed by literal '#0;' -- oracle ACCEPTS.
    expect(() => parse('<system name="t"><t>a&#38;#0;b</t></system>')).not.toThrow();
  });
});

// --- valid-ref RESOLUTION parity: byte-exact model + canonical --------------- #

interface CharrefCase {
  name: string;
  xml: string;
  model: string;
  canonical: string;
}

const HERE = dirname(fileURLToPath(import.meta.url));
const cases: CharrefCase[] = JSON.parse(
  readFileSync(join(HERE, "fixtures", "charref.json"), "utf-8"),
) as CharrefCase[];

describe("valid refs resolve byte-identically to the oracle", () => {
  it("loaded the charref fixtures", () => {
    expect(cases.length).toBeGreaterThanOrEqual(3);
  });

  for (const c of cases) {
    it(`${c.name} model`, () => {
      const actual = serializeModel(parse(c.xml));
      const diff = byteDiff(actual, c.model, `${c.name}/model`);
      expect(diff.equal, diff.message).toBe(true);
    });
    it(`${c.name} canonical`, () => {
      const actual = canonicalize(c.xml);
      const diff = byteDiff(actual, c.canonical, `${c.name}/canonical`);
      expect(diff.equal, diff.message).toBe(true);
    });
  }
});
