/**
 * Normalizer parity + idempotence suite (issue #11).
 *
 * PARITY: air-ts `normalize()` (normalize -> canonicalize, the oracle's
 * save_design path) is byte-diffed against oracle references generated by
 * scripts/gen-patch-refs.py for every input under
 * tests/patch_fixtures/normalize_cases/. Those inputs cover the
 * tests/test_normalizer.py coercion shapes AND the v0.2.4 README input forms
 * (net-owned <node> connectivity, <parameter> -> <value>, lowercase BJT pins,
 * missing net roles, <simulation_profile solver=...>), plus the dark-activated
 * transistor-lamp regression (the "components with no wires" shape).
 *
 * IDEMPOTENCE (acceptance criterion): normalize(normalize(x)) == normalize(x).
 * Applying the normalizer to already-normalized output must be a fixed point.
 * Verified across ALL golden-corpus designs (>=15) AND every normalizer fixture.
 * Corpus designs are discovered dynamically via the shared harness (no design
 * name is hard-coded -- guardrails R4 / harness honesty).
 */

import { readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { describe, expect, it } from "vitest";
import { normalize } from "../src/index.js";
import { byteDiff, discoverDesigns, readText } from "./harness.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const CASE_DIR = join(HERE, "patch_fixtures", "normalize_cases");

interface NormalizeCase {
  name: string;
  inputPath: string;
  expectedPath: string;
}

function discoverNormalizeCases(): NormalizeCase[] {
  const cases: NormalizeCase[] = [];
  for (const entry of readdirSync(CASE_DIR)) {
    if (!entry.endsWith(".air.xml")) continue;
    if (entry.endsWith(".expected.canon.xml")) continue;
    const base = entry.slice(0, -".air.xml".length);
    cases.push({
      name: base,
      inputPath: join(CASE_DIR, entry),
      expectedPath: join(CASE_DIR, `${base}.expected.canon.xml`),
    });
  }
  cases.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  return cases;
}

const cases = discoverNormalizeCases();

describe("normalizer parity vs the live oracle", () => {
  it("discovered the normalizer fixtures (README forms + regression shape)", () => {
    expect(cases.length).toBeGreaterThanOrEqual(10);
    expect(cases.some((c) => c.name === "dark_activated_transistor_lamp")).toBe(
      true,
    );
  });

  for (const c of cases) {
    it(`${c.name}: normalize() is byte-identical to the oracle`, () => {
      const input = readFileSync(c.inputPath, "utf-8");
      const expected = readFileSync(c.expectedPath, "utf-8");
      const actual = normalize(input);
      const diff = byteDiff(actual, expected, `${c.name}.expected.canon.xml`);
      expect(diff.equal, diff.message).toBe(true);
    });
  }
});

describe("normalize idempotence: normalize(normalize(x)) == normalize(x)", () => {
  // All normalizer fixture inputs.
  for (const c of cases) {
    it(`${c.name}: fixture input is a normalize fixed point`, () => {
      const input = readFileSync(c.inputPath, "utf-8");
      const once = normalize(input);
      const twice = normalize(once);
      const diff = byteDiff(twice, once, `${c.name} idempotence`);
      expect(diff.equal, diff.message).toBe(true);
    });
  }

  // Every golden-corpus design (>=15). The canonical/normalized forms must also
  // be fixed points -- a corpus design fed through normalize twice is stable.
  const designs = discoverDesigns();
  it("discovered the full golden corpus (>=15 designs)", () => {
    expect(designs.length).toBeGreaterThanOrEqual(15);
  });
  for (const design of designs) {
    it(`${design.name}: corpus input is a normalize fixed point`, () => {
      const input = readText(design.inputPath);
      const once = normalize(input);
      const twice = normalize(once);
      const diff = byteDiff(twice, once, `${design.name} idempotence`);
      expect(diff.equal, diff.message).toBe(true);
    });
  }
});
