/**
 * Ordering / multi-section regression suite (issue #8 rework round 1).
 *
 * PROVENANCE: fixtures/ordering.json is generated by running each reproducer
 * design through the LIVE Python oracle (validate_tree(tree) + validate_ir(ir),
 * exporter serialization; model_to_dict for the parser case) -- the expected
 * strings are oracle output verbatim, not hand-written. Regenerate with the
 * script recorded in PR #79 (rework round 1) if the oracle changes.
 *
 * What these lock down (verifier's five reproducers + one audit finding):
 *   A1  components with integer-like ids "2","1" in that DOCUMENT order must
 *       report "2" first -- plain JS objects iterate integer-like keys
 *       numerically and reversed the order (and the diag ids with it).
 *   A2  pins "2","1" referencing unknown nets: UNKNOWN_NET order follows
 *       document order, not numeric key order.
 *   A3  duplicate net ids "10","2": DUPLICATE_ID reports "10" first
 *       (first-seen order of the counts dict).
 *   A4  THE SEVERE ONE: a generic_load whose pins are named "2","1" (doc order
 *       2,1). `list(pins)[0]` is pin "2" -> the 0.7A load lands on v33, so the
 *       oracle fires RAIL_LOAD_EXCEEDS_REGULATOR_LIMIT AND SOURCE_OVERLOADED.
 *       The pre-rework port resolved pin "1" first, attributed the load to gnd,
 *       and emitted NEITHER -- silently missing electrical diagnostics.
 *   B   a duplicate id split across TWO <nets> sections: the oracle's
 *       findall("./nets/net") spans all sections; a first-section-only scan
 *       missed the duplicate entirely.
 *   S   (audit finding, same family as B) a test with TWO <setup> sections:
 *       the oracle's test.findall("./setup/*") collects children of every
 *       <setup>; byte-checks BOTH diagnostics.json and model.json.
 *
 * All comparisons are strict byte-diffs of the full serialized payloads
 * (AGENTS.md rule 4) -- not code-presence checks -- so order, ids, messages,
 * and numeric payloads are all locked.
 */

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { validateToJson, parse, serializeModel } from "../src/index.js";
import { byteDiff } from "./harness.js";

interface OrderingCase {
  name: string;
  xml: string;
  diagnostics: string;
  model?: string;
}

const HERE = dirname(fileURLToPath(import.meta.url));
const cases: OrderingCase[] = JSON.parse(
  readFileSync(join(HERE, "fixtures", "ordering.json"), "utf-8"),
) as OrderingCase[];

it("loads all six ordering reproducers", () => {
  expect(cases.map((c) => c.name.split("_")[0]).sort()).toEqual(["A1", "A2", "A3", "A4", "B", "S"]);
});

describe("ordering regressions: diagnostics.json byte-identical to the oracle", () => {
  for (const c of cases) {
    it(c.name, () => {
      const actual = validateToJson(c.xml);
      const diff = byteDiff(actual, c.diagnostics, `${c.name}/diagnostics`);
      expect(diff.equal, diff.message).toBe(true);
    });
  }
});

describe("ordering regressions: model.json byte-identical where the parser is implicated", () => {
  for (const c of cases.filter((c) => c.model !== undefined)) {
    it(c.name, () => {
      const actual = serializeModel(parse(c.xml));
      const diff = byteDiff(actual, c.model as string, `${c.name}/model`);
      expect(diff.equal, diff.message).toBe(true);
    });
  }
});

describe("A4 semantic guard: the load-budget diagnostics are PRESENT", () => {
  // Belt-and-suspenders beyond the byte-diff: the failure mode was silent
  // ABSENCE, so assert presence explicitly (a regenerated fixture that lost
  // these codes would otherwise still byte-match).
  it("RAIL_LOAD_EXCEEDS_REGULATOR_LIMIT and SOURCE_OVERLOADED both fire", () => {
    const a4 = cases.find((c) => c.name.startsWith("A4"));
    expect(a4).toBeDefined();
    const payload = JSON.parse(validateToJson((a4 as OrderingCase).xml)) as {
      diagnostics: Array<{ code: string }>;
    };
    const codes = payload.diagnostics.map((d) => d.code);
    expect(codes).toContain("RAIL_LOAD_EXCEEDS_REGULATOR_LIMIT");
    expect(codes).toContain("SOURCE_OVERLOADED");
  });
});
