/**
 * Patch-engine parity suite (issue #11): air-ts applyPatch/previewPatch vs the
 * LIVE Python oracle, byte-for-byte, over the fixtures in
 * tests/patch_fixtures/patch_designs/.
 *
 * Every reference here is oracle-generated by scripts/gen-patch-refs.py (which
 * calls air.patches / air.canonicalizer, exactly like the service layer) --
 * never hand-written. Each design has one or more patches; a patch is either:
 *   - VALID  -> a `<design>.<label>.expected.canon.xml` (apply output,
 *               canonicalized) and a `<design>.<label>.preview.json` (the
 *               previewPatch structured diff). Both are byte-diffed.
 *   - INVALID -> a `<design>.<label>.error.txt` holding the oracle's
 *               `ValueError: <message>`. air-ts must throw PatchError with the
 *               byte-identical message (same rejection shape -- the registry
 *               declares no PATCH- codes, so raw messages ARE the contract).
 *
 * The differential-probe cases (numeric_nets.*) are OUR designs, chosen to
 * stress the house porting traps: numeric-looking net ids (Map-key ordering),
 * targeting a nonexistent component, a conflicting two-op patch (remove then
 * replace the removed node), an empty (reason-only) patch, and each invalid-op
 * class. The named ADC-divider case (adc_divider.*) is the issue's example:
 * examples/failing/fix_bad_adc_divider.patch.xml applied to the golden-corpus
 * ADC-divider input (copied byte-faithfully into the fixture tree by the
 * generator).
 */

import { readFileSync, readdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { describe, expect, it } from "vitest";
import { applyPatch, previewPatch, PatchError } from "../src/index.js";
import { byteDiff } from "./harness.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const DESIGN_DIR = join(HERE, "patch_fixtures", "patch_designs");

interface PatchCase {
  stem: string; // "<design>.<label>"
  designPath: string;
  patchPath: string;
  canonPath: string;
  previewPath: string;
  errorPath: string;
  isError: boolean;
}

function designKeyFor(patchStem: string, designKeys: string[]): string | null {
  for (const key of designKeys) {
    if (patchStem === key || patchStem.startsWith(key + ".")) return key;
  }
  return null;
}

function discoverPatchCases(): PatchCase[] {
  const entries = readdirSync(DESIGN_DIR);
  const designKeys = entries
    .filter((e) => e.endsWith(".design.air.xml"))
    .map((e) => e.slice(0, -".design.air.xml".length));
  const cases: PatchCase[] = [];
  for (const entry of entries) {
    if (!entry.endsWith(".patch.xml")) continue;
    const stem = entry.slice(0, -".patch.xml".length);
    const designKey = designKeyFor(stem, designKeys);
    if (designKey === null) continue;
    const errorPath = join(DESIGN_DIR, `${stem}.error.txt`);
    cases.push({
      stem,
      designPath: join(DESIGN_DIR, `${designKey}.design.air.xml`),
      patchPath: join(DESIGN_DIR, entry),
      canonPath: join(DESIGN_DIR, `${stem}.expected.canon.xml`),
      previewPath: join(DESIGN_DIR, `${stem}.preview.json`),
      errorPath,
      isError: existsSync(errorPath),
    });
  }
  cases.sort((a, b) => (a.stem < b.stem ? -1 : a.stem > b.stem ? 1 : 0));
  return cases;
}

const cases = discoverPatchCases();

/** Parse a recorded `<Type>: <message>` oracle-error line into its parts. */
function parseRecordedError(errorText: string): { type: string; message: string } {
  const line = errorText.replace(/\r?\n$/, "");
  const idx = line.indexOf(": ");
  if (idx === -1) return { type: "", message: line };
  return { type: line.slice(0, idx), message: line.slice(idx + 2) };
}

describe("patch engine parity vs the live oracle", () => {
  it("discovered at least the ADC-divider case and the differential probes", () => {
    expect(cases.length).toBeGreaterThanOrEqual(7);
    expect(cases.some((c) => c.stem.startsWith("adc_divider"))).toBe(true);
  });

  for (const c of cases) {
    if (c.isError) {
      it(`${c.stem}: applyPatch rejects like the oracle`, () => {
        const design = readFileSync(c.designPath, "utf-8");
        const patch = readFileSync(c.patchPath, "utf-8");
        const recorded = parseRecordedError(readFileSync(c.errorPath, "utf-8"));
        let thrown: unknown;
        try {
          applyPatch(design, patch);
        } catch (err) {
          thrown = err;
        }
        expect(thrown, `${c.stem}: expected applyPatch to throw`).toBeInstanceOf(
          PatchError,
        );
        if (recorded.type === "ValueError") {
          // The contract class: patches.py raises ValueError; PatchError must
          // carry the byte-identical message.
          expect((thrown as PatchError).message).toBe(recorded.message);
        } else {
          // DOCUMENTED DIVERGENCE class (PR #87 rework r1, F2): the oracle
          // crashed INTERNALLY (e.g. ElementPath's TypeError on a mangled
          // predicate from the quote-blind rsplit). Both engines must REJECT,
          // but air-ts raises a clean PatchError instead of mimicking an
          // interpreter-internal message. The air-ts message for the known
          // slash-predicate case is pinned in patch_probes.test.ts (probe 8);
          // here we assert the rejection class only.
          expect(recorded.type.length).toBeGreaterThan(0);
        }
      });
      continue;
    }

    it(`${c.stem}: applyPatch is byte-identical to the oracle canonical output`, () => {
      const design = readFileSync(c.designPath, "utf-8");
      const patch = readFileSync(c.patchPath, "utf-8");
      const expected = readFileSync(c.canonPath, "utf-8");
      const actual = applyPatch(design, patch);
      const diff = byteDiff(actual, expected, `${c.stem}.expected.canon.xml`);
      expect(diff.equal, diff.message).toBe(true);
    });

    it(`${c.stem}: previewPatch is byte-identical to the oracle preview JSON`, () => {
      const design = readFileSync(c.designPath, "utf-8");
      const patch = readFileSync(c.patchPath, "utf-8");
      const expected = readFileSync(c.previewPath, "utf-8");
      // The oracle writes json.dumps(preview, indent=2) + "\n". Match that shape.
      const actual = JSON.stringify(previewPatch(design, patch), null, 2) + "\n";
      const diff = byteDiff(actual, expected, `${c.stem}.preview.json`);
      expect(diff.equal, diff.message).toBe(true);
    });
  }
});
