/**
 * Issue #60 (air-ts side) -- the emitter backs a part-level `spice_model` with a
 * REAL `.model` card from the registry model source (samples/standard.bjt), and
 * stays BYTE-IDENTICAL to the Python oracle.
 *
 * The design + oracle reference live in repo-root `tests/spice_models/`, SHARED
 * with the Python suite (tests/test_spice_model_cards.py) so a single
 * `bjt_2n2222_switch.expected.cir` is the byte-exact contract both engines must
 * reproduce (air-ts == oracle == reference). The reference is regenerated by
 * `packages/air-ts/scripts/gen-spice-model-refs.py` from the live oracle.
 *
 * KEY cases FAIL on the pre-fix code:
 *   - the 2N2222 design errors UNDEFINED_SPICE_MODEL, so `validate` reports it and
 *     `compileDesign` REFUSES (returns null);
 *   - the emitter has no `.model 2N2222` card, so the reference byte-diff fails.
 * Discrimination (FOOBAR999 / undefined subckt) and the corpus guard hold both
 * pre- and post-fix.
 */

import { readFileSync, readdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { describe, it, expect } from "vitest";
import { validate, validateToJson, hasErrors } from "../src/index.js";
import { compileDesign } from "../src/emit/spice.js";
import { byteDiff } from "./harness.js";

const HERE = dirname(fileURLToPath(import.meta.url));
// packages/air-ts/tests -> repo root is three levels up.
const REPO_ROOT = join(HERE, "..", "..", "..");
const DESIGN_DIR = join(REPO_ROOT, "tests", "spice_models");
const DESIGN_PATH = join(DESIGN_DIR, "bjt_2n2222_switch.air.xml");
const EXPECTED_CIR = join(DESIGN_DIR, "bjt_2n2222_switch.expected.cir");
const CORPUS_DIR = join(REPO_ROOT, "tests", "golden_corpus");

const DESIGN_XML = readFileSync(DESIGN_PATH, "utf-8");

/**
 * Real Gummel-Poon parameters of the 2N2222 card in samples/standard.bjt (the
 * data the emitter must carry). Compared case-insensitively -- the exact bytes
 * are pinned by the committed oracle reference, this pins the real DATA.
 */
const REAL_2N2222_PARAMS = [
  "IS=1E-14", "VAF=100", "BF=200", "IKF=0.3", "XTB=1.5", "BR=3",
  "CJC=8E-12", "CJE=25E-12", "TR=100E-9", "TF=400E-12",
  "ITF=1", "VTF=2", "XTF=3", "RB=10", "RC=.3", "RE=.2",
];

/** Every BJT model NAME in samples/standard.bjt -- the exhaustive backed set. */
const STANDARD_BJT_NAMES = [
  "2N2222", "2N2907", "2N3904", "2N3906",
  "FZT849", "ZTX1048A", "2N4124", "2N4126", "BC547B",
];

function modelCardLine(netlist: string): string | undefined {
  return netlist.split("\n").find((l) => l.startsWith(".model 2N2222"));
}

function corpusDesigns(): string[] {
  return readdirSync(CORPUS_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory() && existsSync(join(CORPUS_DIR, e.name, "input.air.xml")))
    .map((e) => e.name)
    .sort();
}

// --------------------------------------------------------------------------- //
// Validation: the 2N2222 design is BACKED (no UNDEFINED_SPICE_MODEL).          //
// --------------------------------------------------------------------------- //

describe("#60 air-ts: a real 2N2222 design validates clean", () => {
  it("does not error UNDEFINED_SPICE_MODEL and has no errors", () => {
    const diags = validate(DESIGN_XML);
    const codes = diags.map((d) => d.code);
    expect(codes, `diagnostics: ${JSON.stringify(codes)}`).not.toContain("UNDEFINED_SPICE_MODEL");
    expect(hasErrors(diags), `errors: ${JSON.stringify(diags.filter((d) => d.severity === "error"))}`).toBe(false);
  });
});

// --------------------------------------------------------------------------- //
// Emission: the real .model 2N2222 card + byte parity with the oracle.         //
// --------------------------------------------------------------------------- //

describe("#60 air-ts: compileDesign emits the real 2N2222 card", () => {
  it("compiles (does not refuse) and the netlist carries a single joined 2N2222 card", () => {
    const artifacts = compileDesign(DESIGN_XML);
    expect(artifacts, "the backed 2N2222 design must compile, not be refused").not.toBeNull();
    const card = modelCardLine(artifacts!.netlist);
    expect(card, `no '.model 2N2222' line in:\n${artifacts!.netlist}`).toBeDefined();
    expect(card!.trimEnd().endsWith(")"), `card is not a single closed line: ${card}`).toBe(true);
    expect(card!.toUpperCase()).toContain("NPN(");
    for (const token of REAL_2N2222_PARAMS) {
      expect(card!.toUpperCase(), `card missing real param ${token}: ${card}`).toContain(token.toUpperCase());
    }
    // ngspice-46 rejects the raw source's non-numeric `mfg=Philips` annotation,
    // so the EMITTED card must not carry it.
    expect(card!.toUpperCase()).not.toContain("PHILIPS");
    expect(card!.toUpperCase()).not.toContain("MFG=");
  });

  it("is byte-identical to the committed oracle reference (air-ts == Python)", () => {
    const artifacts = compileDesign(DESIGN_XML);
    expect(artifacts, "expected a compiled netlist").not.toBeNull();
    const expected = readFileSync(EXPECTED_CIR, "utf-8");
    const diff = byteDiff(artifacts!.netlist, expected, "bjt_2n2222_switch.expected.cir");
    expect(diff.equal, diff.message).toBe(true);
  });

  it("compiles deterministically (same bytes twice)", () => {
    const a = compileDesign(DESIGN_XML);
    const b = compileDesign(DESIGN_XML);
    expect(a).not.toBeNull();
    expect(a!.netlist).toBe(b!.netlist);
  });
});

// --------------------------------------------------------------------------- //
// Discrimination preserved (holds pre- AND post-fix).                          //
// --------------------------------------------------------------------------- //

describe("#60 air-ts: discrimination is not weakened", () => {
  const FOOBAR =
    '<system name="foobar" ir_version="0.1"><metadata><title>t</title></metadata>' +
    '<nets><net id="c" role="analog_signal"/><net id="b" role="analog_signal"/><net id="gnd" role="ground"/></nets>' +
    '<components><component id="Q1" type="bjt" spice_model="FOOBAR999">' +
    '<pin name="C" net="c"/><pin name="B" net="b"/><pin name="E" net="gnd"/></component></components>' +
    "<tests/><simulation_profiles/></system>";

  const UNDEF_SUBCKT =
    '<system name="subx" ir_version="0.1"><metadata><title>t</title></metadata>' +
    '<nets><net id="a" role="analog_signal"/><net id="b" role="analog_signal"/><net id="gnd" role="ground"/></nets>' +
    '<components><component id="U1" type="diode" spice_subckt="LM358">' +
    '<pin name="a" net="a"/><pin name="c" net="b"/></component></components>' +
    "<tests/><simulation_profiles/></system>";

  it("FOOBAR999 (not in standard.bjt) still errors UNDEFINED_SPICE_MODEL", () => {
    expect(validate(FOOBAR).map((d) => d.code)).toContain("UNDEFINED_SPICE_MODEL");
  });

  it("an undefined spice_subckt still errors UNDEFINED_SPICE_MODEL", () => {
    expect(validate(UNDEF_SUBCKT).map((d) => d.code)).toContain("UNDEFINED_SPICE_MODEL");
  });
});

// --------------------------------------------------------------------------- //
// Golden-corpus guard: the fix is a no-op on the corpus.                       //
// --------------------------------------------------------------------------- //

describe("#60 air-ts: golden-corpus guard", () => {
  it("no corpus design references a now-backed standard.bjt model", () => {
    const offenders: string[] = [];
    for (const name of corpusDesigns()) {
      const xml = readFileSync(join(CORPUS_DIR, name, "input.air.xml"), "utf-8");
      for (const model of STANDARD_BJT_NAMES) {
        if (xml.includes(`"${model}"`)) offenders.push(`${name}:${model}`);
      }
    }
    expect(offenders, `corpus references a backed model: ${JSON.stringify(offenders)}`).toEqual([]);
  });

  it("corpus designs that error UNDEFINED_SPICE_MODEL today still do (and still match diagnostics.json)", () => {
    let count = 0;
    for (const name of corpusDesigns()) {
      const diagPath = join(CORPUS_DIR, name, "diagnostics.json");
      if (!existsSync(diagPath)) continue;
      const expected = readFileSync(diagPath, "utf-8");
      if (!expected.includes("UNDEFINED_SPICE_MODEL")) continue;
      const xml = readFileSync(join(CORPUS_DIR, name, "input.air.xml"), "utf-8");
      expect(validate(xml).map((d) => d.code), `${name} lost UNDEFINED_SPICE_MODEL`).toContain(
        "UNDEFINED_SPICE_MODEL",
      );
      // Byte-parity is unchanged too (the fix must not touch this fixture).
      expect(validateToJson(xml)).toBe(expected);
      count++;
    }
    expect(count, "expected >= 4 corpus designs with UNDEFINED_SPICE_MODEL").toBeGreaterThanOrEqual(4);
  });
});
