from __future__ import annotations

from pathlib import Path

from .artifacts import Artifact, CompileResult
from .firmware import firmware_platformio_settings
from .model import SystemIR
from .registry import MCUS


def compile_renode(ir: SystemIR, out_dir: Path, feedback_commands: list[str] | None = None) -> CompileResult:
    renode_dir = out_dir / "renode"
    renode_dir.mkdir(parents=True, exist_ok=True)

    mcu_comp = next((c for c in ir.components.values() if c.type == "mcu"), None)
    mcu_spec = MCUS.get(mcu_comp.part) if mcu_comp else None

    board = firmware_platformio_settings(ir)["board"]

    # 1. Generate .repl (Platform)
    repl_lines = ["// Generated by AIR"]
    if mcu_spec:
        # CPU
        cpu = mcu_spec.get("cpu", {})
        repl_lines.append(f"cpu: CPU.{cpu.get('model', 'CortexM')} @ sysbus")
        
        # Memory
        for mem in mcu_spec.get("memory", []):
            repl_lines.append(f"{mem['name']}: Memory.MappedMemory @ sysbus {mem['address']}")
            repl_lines.append(f"    size: {mem['size']}")
            
        # Peripherals
        for name, p in mcu_spec.get("peripherals", {}).items():
            if isinstance(p, dict) and "type" in p:
                repl_lines.append(f"{name.lower()}: {p['type']} @ sysbus {p['address']}")
    else:
        repl_lines.append(f"// Placeholder for {mcu_comp.part if mcu_comp else 'Unknown'}")

    platform = renode_dir / "platform.repl"
    platform.write_text("\n".join(repl_lines) + "\n", encoding="utf-8")

    # 2. Generate .resc (Script)
    feedback_script = ""
    if feedback_commands:
        feedback_script = "\n".join(feedback_commands) + "\n"

    script = renode_dir / "run.resc"
    # PlatformIO writes the ELF to .pio/build/<env>/firmware.elf, and the env is
    # named after the board (see firmware.compile_firmware). Keep these in lockstep
    # so LoadELF resolves after a real `pio run`.
    elf_path = f"../firmware/.pio/build/{board}/firmware.elf"

    script.write_text(
        f"""mach create "{mcu_comp.id if mcu_comp else 'mcu'}"
machine LoadPlatformDescription @platform.repl
sysbus LoadELF @{elf_path}
{feedback_script}start
""",
        encoding="utf-8",
    )

    robot = renode_dir / "test.robot"
    robot.write_text(
        """*** Settings ***
Documentation  Generated AIR placeholder Renode test.

*** Test Cases ***
Firmware boots
    Log To Console  Renode placeholder test; exact MCU model pending.
""",
        encoding="utf-8",
    )
    return CompileResult(
        target="renode",
        success=True,
        artifacts=[
            Artifact(str(platform), "renode_platform"),
            Artifact(str(script), "renode_script"),
            Artifact(str(robot), "renode_test"),
        ],
        diagnostics=[],
    )
