from __future__ import annotations

from pathlib import Path

from .artifacts import Artifact, CompileResult
from .diagnostics import DiagnosticBuilder
from .model import Component, SystemIR, Test
from .units import spice_value


GROUND_NAMES = {"gnd", "0"}

# The generic device models the compiler emits a ``.model`` card for in every
# netlist (see BUILTIN_MODEL_CARDS below). A component ``spice_model`` is only
# simulable if it names one of these -- the registry stores no per-part SPICE
# parameters, so a device line referencing any OTHER model name (e.g. BSS138,
# 1N5819) has no ``.model``/``.subckt`` behind it and ngspice cannot run it.
# Validation (validation._validate_spice_models) uses this set as the source of
# truth for which model names are backed. Case-insensitive compare there.
BUILTIN_SPICE_MODELS = frozenset({"NMOS", "PMOS", "NPN", "PNP", "D"})

# No ``.subckt`` definitions are ever emitted, so any ``spice_subckt`` reference
# (X_ line) is unbacked. Kept as an explicit (empty) set so the intent -- "we
# define zero subcircuits today" -- is visible and easy to extend later.
BUILTIN_SPICE_SUBCKTS: frozenset[str] = frozenset()

BUILTIN_MODEL_CARDS = [
    ".model NMOS NMOS(Vto=1.5 Kp=1)",
    ".model PMOS PMOS(Vto=-1.5 Kp=1)",
    ".model NPN NPN(Bf=100)",
    ".model PNP PNP(Bf=100)",
    ".model D D",
]


def compile_spice(
    ir: SystemIR,
    out_dir: Path,
    test: Test | None = None,
    raw_stimulus: list[str] | None = None,
    initial_conditions: dict[str, float] | None = None,
    extra_probes: list[str] | None = None,
) -> CompileResult:
    builder = DiagnosticBuilder()
    diagnostics = []
    spice_dir = out_dir / "spice"
    wave_dir = out_dir / "waveforms"
    spice_dir.mkdir(parents=True, exist_ok=True)
    wave_dir.mkdir(parents=True, exist_ok=True)

    lines = ["* Generated by AIR", ".options filetype=ascii", *BUILTIN_MODEL_CARDS]
    
    if initial_conditions:
        ic_line = ".ic " + " ".join([f"V({_spice_net(net)})={val}" for net, val in initial_conditions.items()])
        lines.append(ic_line)

    # Nets already driven by a voltage_source component: a test set_voltage on the
    # same net would emit a second parallel source and make ngspice abort (vsource
    # loop). The component source wins; the redundant test source is skipped.
    component_source_nets = {
        list(component.pins.values())[0].net
        for component in ir.components.values()
        if component.type == "voltage_source" and component.value and len(component.pins) >= 2
    }
    voltage_sources = _test_voltage_sources(test)
    for source_name, (net, value) in voltage_sources.items():
        if net in component_source_nets:
            continue
        lines.append(f"{source_name} {_spice_net(net)} 0 DC {spice_value(value)}")

    if raw_stimulus:
        lines.extend(raw_stimulus)
    else:
        lines.extend(_mcu_stimulus_lines(ir))


    for component in sorted(ir.components.values(), key=lambda c: c.id):
        emitted = _component_line(component, test)
        if emitted:
            lines.append(emitted)
        elif component.type in {"mcu", "generic_load"}:
            continue
        elif component.type == "ldo":
            lines.append(_ldo_line(component))
        else:
            diagnostics.append(builder.make("warning", "compiler", "UNSUPPORTED_SPICE_COMPONENT", f"Component {component.id} type {component.type} is not emitted to SPICE.", [component.id]))

    duration = test.duration if test and test.duration else "100ms"
    lines.extend(
        [
            f".tran 1u {spice_value(duration)}",
            ".control",
            "run",
        ]
    )
    if test:
        assertion_nets = {a.get("net", "") for a in test.assertions if a.get("op") == "assert_voltage" and a.get("net")}
        probe_nets = sorted(assertion_nets | set(extra_probes or []))
        for net in probe_nets:
            lines.append(f"wrdata ../waveforms/{test.id}_{net}.csv v({_spice_net(net)})")
    lines.extend([".endc", ".end", ""])

    netlist = spice_dir / "main.cir"
    netlist.write_text("\n".join(lines), encoding="utf-8")
    probes = spice_dir / "probes.json"
    probes.write_text("{}\n", encoding="utf-8")
    return CompileResult(
        target="spice",
        success=not any(d.severity == "error" for d in diagnostics),
        artifacts=[
            Artifact(str(netlist), "spice_netlist"),
            Artifact(str(probes), "spice_control"),
        ],
        diagnostics=diagnostics,
    )


def _component_line(component: Component, test: Test | None = None) -> str | None:
    pins = list(component.pins.values())
    if component.type == "resistor" and component.value and len(pins) >= 2:
        return f"R_{component.id} {_spice_net(pins[0].net)} {_spice_net(pins[1].net)} {spice_value(component.value)}"
    if component.type == "capacitor" and component.value and len(pins) >= 2:
        return f"C_{component.id} {_spice_net(pins[0].net)} {_spice_net(pins[1].net)} {spice_value(component.value)}"
    if component.type == "voltage_source" and component.value and len(pins) >= 2:
        return f"V_{component.id} {_spice_net(pins[0].net)} {_spice_net(pins[1].net)} DC {spice_value(component.value)}"
    if component.type == "current_source" and component.value and len(pins) >= 2:
        return f"I_{component.id} {_spice_net(pins[0].net)} {_spice_net(pins[1].net)} DC {spice_value(component.value)}"
    if component.type == "bjt" and len(pins) >= 3:
        c = component.pins.get("C")
        b = component.pins.get("B")
        e = component.pins.get("E")
        model = component.spice_model or "NPN"
        if c and b and e:
            return f"Q_{component.id} {_spice_net(c.net)} {_spice_net(b.net)} {_spice_net(e.net)} {model}"
    if component.type == "mosfet" and len(pins) >= 3:
        g = component.pins.get("G")
        d = component.pins.get("D")
        s = component.pins.get("S")
        model = component.spice_model or "NMOS"
        if g and d and s:
            return f"M_{component.id} {_spice_net(d.net)} {_spice_net(g.net)} {_spice_net(s.net)} {_spice_net(s.net)} {model}"
    if component.type == "diode" and len(pins) >= 2:
        a = component.pins.get("a")
        c = component.pins.get("c")
        model = component.spice_model or "D"
        if a and c:
            return f"D_{component.id} {_spice_net(a.net)} {_spice_net(c.net)} {model}"
    if component.spice_subckt:
        # Generic subcircuit emission
        pin_nets = " ".join(_spice_net(p.net) for p in pins)
        return f"X_{component.id} {pin_nets} {component.spice_subckt}"
    if component.type == "generic_load" and len(pins) >= 2:
        step = _test_load_step(test, component.id)
        if step:
            start, stop, at, rise = step
            return (
                f"I_{component.id} {_spice_net(pins[0].net)} {_spice_net(pins[1].net)} "
                f"PULSE({spice_value(start)} {spice_value(stop)} {spice_value(at)} {spice_value(rise)} {spice_value(rise)} 1s 2s)"
            )
        current = _test_current(test, component.id) or component.properties.get("current") or component.value
        if current:
            return f"I_{component.id} {_spice_net(pins[0].net)} {_spice_net(pins[1].net)} DC {spice_value(current)}"
    return None


def _mcu_stimulus_lines(ir: SystemIR) -> list[str]:
    lines = []
    for task in ir.firmware_tasks.values():
        project = ir.firmware_projects.get(task.target)
        if not project:
            continue
        mcu = ir.components.get(project.target)
        if not mcu:
            continue

        for op in task.operations:
            if op["op"] == "write_gpio":
                pin_name = op.get("pin")
                value = op.get("value")
                pin = mcu.pins.get(pin_name)
                if not pin:
                    continue

                if task.period and value == "high":
                    # Simple PULSE translation for periodic high-low
                    period = spice_value(task.period)
                    # Find subsequent delay
                    op_idx = task.operations.index(op)
                    ton = "1ms"
                    for next_op in task.operations[op_idx+1:]:
                        if next_op["op"] == "delay":
                            ton = spice_value(next_op.get("duration", "1ms"))
                            break
                    lines.append(f"V_STIM_{mcu.id}_{pin_name} {_spice_net(pin.net)} 0 PULSE(0 3.3 0 1u 1u {ton} {period})")
                elif not task.period:
                    v = "3.3" if value == "high" else "0"
                    lines.append(f"V_STIM_{mcu.id}_{pin_name} {_spice_net(pin.net)} 0 DC {v}")
    return lines


def _ldo_line(component: Component) -> str:
    in_net = component.pins.get("in")
    out_net = component.pins.get("out")
    gnd_net = component.pins.get("gnd")
    vout = component.properties.get("vout", "3.3V")
    v_dropout = component.properties.get("v_dropout", "0.2V")
    iq = component.properties.get("iq", "0")
    
    if not in_net or not out_net or not gnd_net:
        return f"* LDO {component.id} skipped: missing in/out/gnd"
    
    lines = []
    # Quiescent current
    if spice_value(iq) != "0":
        lines.append(f"I_{component.id}_iq {_spice_net(in_net.net)} {_spice_net(gnd_net.net)} DC {spice_value(iq)}")
    
    # Voltage source with dropout: Vout = min(Vtarget, Vin - Vdropout)
    # Using SPICE 'limit' or 'min' if supported, or just a simple expression.
    # Ngspice support min(a, b)
    expr = f"min({spice_value(vout)}, V({_spice_net(in_net.net)}) - {spice_value(v_dropout)})"
    lines.append(f"E_{component.id} {_spice_net(out_net.net)} {_spice_net(gnd_net.net)} VALUE = {{ {expr} }}")
    
    return "\n".join(lines)


def _test_voltage_sources(test: Test | None) -> dict[str, tuple[str, str]]:
    if not test:
        return {}
    return {
        f"V_{net.upper()}": (net, value)
        for net, value in sorted(test.setup.items())
        if not net.startswith("current:") and not net.startswith("load_step:")
    }


def _test_current(test: Test | None, component_id: str) -> str | None:
    if not test:
        return None
    return test.setup.get(f"current:{component_id}")


def _test_load_step(test: Test | None, component_id: str) -> tuple[str, str, str, str] | None:
    if not test:
        return None
    encoded = test.setup.get(f"load_step:{component_id}")
    if not encoded:
        return None
    parts = encoded.split(",")
    if len(parts) != 4 or not parts[0] or not parts[1]:
        return None
    return parts[0], parts[1], parts[2], parts[3]


def _spice_net(net: str) -> str:
    return "0" if net.lower() in GROUND_NAMES else net
